name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    environment: Production
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag discord-voice-poc:latest

      - name: Run the Docker container
        run: |
          docker run -d \
            -e DISCORD_TOKEN=${DISCORD_TOKEN} \
            --name discord-voice-poc \
            discord-voice-poc:latest
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
