name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    environment: Production
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write # Required to push to GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Log into GitHub Container Registry (GHCR)
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Run the Docker container
        run: |
          docker run -d \
            -e DISCORD_TOKEN=${DISCORD_TOKEN} \
            --name discord-voice-poc \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}

      # Push the Docker image to GHCR
      - name: Push Docker image to GHCR
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
