# This workflow will install dependencies, cache them, and run the server for the school-closing project

name: School Closing CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: "npm"

      - run: npm ci

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag discord-voice-poc:latest

      - name: Run the Docker container
        run: |
          docker run -d \
            -e DISCORD_TOKEN=${DISCORD_TOKEN} \
            --name discord-voice-poc \
            discord-voice-poc:latest
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
